"""
Ontology generation service
interface 1:Analyze text content,Generate entity and relationship type definitions suitable for social simulation
"""

import json
import logging
import re
from typing import Dict, Any, List, Optional
from ..utils.llm_client import LLMClient
from ..utils.locale import get_language_instruction
from ..utils.file_parser import split_text_into_chunks
from ..utils.ontology import (
    MAX_ONTOLOGY_TYPES,
    normalize_ontology_attributes,
    normalize_ontology_source_targets,
)

logger = logging.getLogger(__name__)


def _to_pascal_case(name: str) -> str:
    """Convert an arbitrary formatted name to PascalCase(Such as 'works_for' -> 'WorksFor', 'person' -> 'Person')"""
    # Split by non-alphanumeric characters
    parts = re.split(r'[^a-zA-Z0-9]+', name)
    # Press again camelCase boundary segmentation(Such as 'camelCase' -> ['camel', 'Case'])
    words = []
    for part in parts:
        words.extend(re.sub(r'([a-z])([A-Z])', r'\1_\2', part).split('_'))
    # Capitalize the first letter of each word,Filter empty string
    result = ''.join(word.capitalize() for word in words if word)
    return result if result else 'Unknown'


def _to_upper_snake_case(name: str) -> str:
    """Convert free-form or camelCase names to SCREAMING_SNAKE_CASE."""

    separated = re.sub(r'([a-z0-9])([A-Z])', r'\1_\2', name.strip())
    normalized = re.sub(r'[^a-zA-Z0-9]+', '_', separated).strip('_').upper()
    if not normalized:
        return "UNKNOWN"
    if normalized[0].isdigit():
        normalized = f"REL_{normalized}"
    return normalized


# System prompt words generated by ontology
ONTOLOGY_SYSTEM_PROMPT = """You are a professional knowledge graph ontology design expert.Your task is to analyze the given text content and simulate the requirements,Designed to fit**Social media public opinion simulation**Entity types and relationship types.

**important:You must output a valid JSON format data,Do not output anything else.**

## Core mission background

we are building a**Social media public opinion simulation system**.in this system:
- Every entity has a voice on social media,interactive,disseminating information"Account number"or"subject"
- Entities affect each other,forward,Comment,respond
- We need to simulate the reactions of all parties and information dissemination paths in public opinion events

Therefore,**The entity must be real in reality,Subjects who can speak out and interact on social media**:

**can be**:
- specific individuals(public figure,parties,opinion leader,Experts and scholars,ordinary people)
- company,enterprise(Including its official account)
- Organizational structure(university,association,NGO,Trade unions etc)
- government departments,regulatory agency
- media organization(newspaper,TV station,self media,website)
- The social media platform itself
- representatives of specific groups(such as alumni association,fan club,rights protection groups etc)

**cannot be**:
- abstract concept(Such as"public opinion","emotions","Trend")
- Topic/topic(Such as"academic integrity","education reform")
- point of view/attitude(Such as"Supporters","Opposition")

## Output format

Please output JSON Format,Contains the following structure:

```json
{
    "entity_types": [
        {
            "name": "Entity type name(English,PascalCase)",
            "description": "short description(English,no more than 100 character)",
            "attributes": [
                {
                    "name": "attribute name(English,snake_case)",
                    "type": "text",
                    "description": "Property description"
                }
            ],
            "examples": ["Example entity 1", "Example entity 2"]
        }
    ],
    "edge_types": [
        {
            "name": "Relationship type name(English,UPPER_SNAKE_CASE)",
            "description": "short description(English,no more than 100 character)",
            "source_targets": [
                {"source": "Source entity type", "target": "target entity type"}
            ],
            "attributes": []
        }
    ],
    "analysis_summary": "A brief analysis of the content of the text"
}
```

## Design Guidelines(extremely important!)

### 1. Entity type design - must be strictly observed

**Quantity requirement:Must be just right 10 entity type**

**Hierarchy requirements(Must contain both concrete type and cover type)**:

yours 10 Entity types must contain the following levels:

A. **Cover type(must contain,put at the end of the list 2 a)**:
   - `Person`: Any type of cover-up for an individual natural person.When a person does not fit into other more specific person types,fall into this category.
   - `Organization`: Types of cover for any organization.When an organization does not belong to another more specific organization type,fall into this category.

B. **concrete type(8 a,Design based on text content)**:
   - Target the main characters that appear in the text,Design more specific types
   - For example:If the text relates to an academic event,can have `Student`, `Professor`, `University`
   - For example:If the text relates to a business event,can have `Company`, `CEO`, `Employee`

**Why do you need a cover-up type**:
- Various characters will appear in the text,Such as"Primary and secondary school teachers","Passerby","A certain netizen"
- If there is no specific type match,they should be classified `Person`
- Same reason,small organization,Temporary groups etc should be classified under `Organization`

**Type-specific design principles**:
- Identify frequently occurring or key character types from text
- Each concrete type should have clear boundaries,avoid overlap
- description The difference between this type and the cover-up type must be clearly stated

### 2. Relationship type design

- Quantity:6-10 a
- Relationships should reflect real connections in social media interactions
- ensure relationship source_targets Covers the entity types you define

### 3. Attribute design

- each entity type 1-3 key attributes
- **Note**:Property name cannot be used `name`,`uuid`,`group_id`,`graph_id`,`created_at`,`summary`(These are system reserved words)
- Recommended:`full_name`, `title`, `role`, `position`, `location`, `description` Wait

## Entity type reference

**personal category(specific)**:
- Student: student
- Professor: Professor/scholar
- Journalist: reporter
- Celebrity: star/internet celebrity
- Executive: executive
- Official: government officials
- Lawyer: lawyer
- Doctor: doctor

**personal category(Keep everything in mind)**:
- Person: any natural person(Used when it does not belong to the above specific types)

**Organization type(specific)**:
- University: College
- Company: company enterprise
- GovernmentAgency: government agencies
- MediaOutlet: media organization
- Hospital: hospital
- School: Primary and secondary schools
- NGO: non-governmental organization

**Organization type(Keep everything in mind)**:
- Organization: any organization(Used when it does not belong to the above specific types)

## Relationship type reference

- WORKS_FOR: working on
- STUDIES_AT: Studied at
- AFFILIATED_WITH: Belong to
- REPRESENTS: represent
- REGULATES: supervision
- REPORTS_ON: report
- COMMENTS_ON: Comment
- RESPONDS_TO: respond
- SUPPORTS: support
- OPPOSES: object
- COLLABORATES_WITH: cooperation
- COMPETES_WITH: competition
"""


class OntologyGenerator:
    """
    ontology generator
    Analyze text content,Generate entity and relationship type definitions
    """

    def __init__(self, llm_client: Optional[LLMClient] = None):
        self.llm_client = llm_client or LLMClient()

    def generate(
        self,
        document_texts: List[str],
        simulation_requirement: str,
        additional_context: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        Generate ontology definition

        Args:
            document_texts: Document text list
            simulation_requirement: Simulation requirement description
            additional_context: extra context

        Returns:
            ontology definition(entity_types, edge_types Wait)
        """
        # Build user messages
        user_message = self._build_user_message(
            document_texts,
            simulation_requirement,
            additional_context
        )

        lang_instruction = get_language_instruction()
        system_prompt = f"{ONTOLOGY_SYSTEM_PROMPT}\n\n{lang_instruction}\nIMPORTANT: Entity type names MUST be in English PascalCase (e.g., 'PersonEntity', 'MediaOrganization'). Relationship type names MUST be in English UPPER_SNAKE_CASE (e.g., 'WORKS_FOR'). Attribute names MUST be in English snake_case. Only description fields and analysis_summary should use the specified language above."
        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_message}
        ]

        # call LLM
        result = self.llm_client.chat_json(
            messages=messages,
            temperature=0.3,
            # Structured ontology responses can exceed 4096 completion tokens,
            # especially when a compatible provider counts hidden reasoning in
            # the same budget. Let the provider use its model-specific limit.
            max_tokens=None,
            max_attempts=2,
        )

        # Validation and post-processing
        result = self._validate_and_process(result)

        return result

    # pass to LLM The maximum length of text(5 Ten thousand words)
    MAX_TEXT_LENGTH_FOR_LLM = 50000
    LONG_TEXT_CHUNK_SIZE = 8000
    LONG_TEXT_CHUNK_OVERLAP = 200
    MAX_LONG_TEXT_CHUNKS = 60
    MIN_LONG_TEXT_EXCERPT = 400

    def _build_user_message(
        self,
        document_texts: List[str],
        simulation_requirement: str,
        additional_context: Optional[str]
    ) -> str:
        """Build user messages"""

        combined_text = self._build_document_context(document_texts)

        message = f"""## Simulation requirements

{simulation_requirement}

## Document content

{combined_text}
"""

        if additional_context:
            message += f"""
## Additional instructions

{additional_context}
"""

        message += """
Please follow the above,Design entity types and relationship types suitable for social opinion simulation.

**rules that must be followed**:
1. Must be output exactly 10 entity type
2. finally 2 Must be a cover-up type:Person(Personal information)and Organization(Organizations keep track of everything)
3. before 8 A specific type designed based on text content
4. All entity types must be real-life subjects that can speak,It cannot be an abstract concept
5. Property name cannot be used name,uuid,group_id,graph_id Wait for reserved words,use full_name,org_name Wait for replacement
"""

        return message

    def _build_document_context(self, document_texts: List[str]) -> str:
        """Building document context for ontology analysis,Long text is sampled in global chunks instead of just cutting off the beginning."""

        combined_text = "\n\n---\n\n".join(document_texts)
        original_length = len(combined_text)

        if original_length <= self.MAX_TEXT_LENGTH_FOR_LLM:
            return combined_text

        chunks = self._collect_document_chunks(document_texts)
        if not chunks:
            return ""

        selected_chunks = self._select_representative_chunks(chunks)
        excerpt_budget = self._calculate_excerpt_budget(len(selected_chunks))
        context = self._render_chunked_context(
            selected_chunks=selected_chunks,
            original_length=original_length,
            total_chunks=len(chunks),
            excerpt_limit=excerpt_budget,
        )

        while len(context) > self.MAX_TEXT_LENGTH_FOR_LLM and excerpt_budget > self.MIN_LONG_TEXT_EXCERPT:
            excerpt_budget = max(self.MIN_LONG_TEXT_EXCERPT, int(excerpt_budget * 0.85))
            context = self._render_chunked_context(
                selected_chunks=selected_chunks,
                original_length=original_length,
                total_chunks=len(chunks),
                excerpt_limit=excerpt_budget,
            )

        if len(context) > self.MAX_TEXT_LENGTH_FOR_LLM:
            marker = "\n\n...(Chunked context has been compressed to fit within the ontology analysis length limit)..."
            context = context[:self.MAX_TEXT_LENGTH_FOR_LLM - len(marker)] + marker

        return context

    def _collect_document_chunks(self, document_texts: List[str]) -> List[Dict[str, Any]]:
        """Collect chunks by document,Keep document and block numbers to facilitate prompt word positioning."""

        all_chunks: List[Dict[str, Any]] = []
        for doc_index, text in enumerate(document_texts, 1):
            doc_chunks = split_text_into_chunks(
                text,
                chunk_size=self.LONG_TEXT_CHUNK_SIZE,
                overlap=self.LONG_TEXT_CHUNK_OVERLAP,
            )
            total_doc_chunks = len(doc_chunks)
            for chunk_index, chunk in enumerate(doc_chunks, 1):
                all_chunks.append({
                    "document_index": doc_index,
                    "chunk_index": chunk_index,
                    "total_document_chunks": total_doc_chunks,
                    "text": chunk,
                })

        return all_chunks

    def _select_representative_chunks(self, chunks: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """Sampling equally spaced from all blocks,Cover the beginning of long articles,middle and end."""

        if len(chunks) <= self.MAX_LONG_TEXT_CHUNKS:
            return chunks

        if self.MAX_LONG_TEXT_CHUNKS <= 1:
            return [chunks[0]]

        last_index = len(chunks) - 1
        selected_indexes = {
            round(i * last_index / (self.MAX_LONG_TEXT_CHUNKS - 1))
            for i in range(self.MAX_LONG_TEXT_CHUNKS)
        }
        return [chunks[i] for i in sorted(selected_indexes)]

    def _calculate_excerpt_budget(self, selected_count: int) -> int:
        """Allocate a character budget to each chunk based on the number of chunks selected."""

        header_budget = 600
        chunk_header_budget = 120 * selected_count
        available = max(
            self.MIN_LONG_TEXT_EXCERPT * selected_count,
            self.MAX_TEXT_LENGTH_FOR_LLM - header_budget - chunk_header_budget,
        )
        return max(self.MIN_LONG_TEXT_EXCERPT, available // max(selected_count, 1))

    def _render_chunked_context(
        self,
        selected_chunks: List[Dict[str, Any]],
        original_length: int,
        total_chunks: int,
        excerpt_limit: int,
    ) -> str:
        """Render long text chunked context."""

        lines = [
            (
                f"[Automatic chunking of long text summaries]Total original text{original_length}word,"
                f"has been divided into{total_chunks}text blocks for global coverage analysis."
            ),
            (
                f"Shown below{len(selected_chunks)}An excerpt from a representative block of text,"
                "Cover the beginning,middle and end;Please design an ontology based on these cross-text clues,Don t just rely on the first paragraph."
            ),
        ]

        for chunk in selected_chunks:
            excerpt = self._excerpt_text(chunk["text"], excerpt_limit)
            lines.append(
                "\n".join([
                    (
                        f"--- Documentation {chunk['document_index']} / "
                        f"Chunking {chunk['chunk_index']}/{chunk['total_document_chunks']} ---"
                    ),
                    excerpt,
                ])
            )

        return "\n\n".join(lines)

    @staticmethod
    def _excerpt_text(text: str, char_limit: int) -> str:
        """Keep the beginning and end of long blocks,Prevent each block from becoming just the beginning again."""

        text = text.strip()
        if len(text) <= char_limit:
            return text

        marker = "\n...(The content in the middle of this section is omitted)...\n"
        if char_limit <= len(marker) + 20:
            return text[:char_limit]

        remaining = char_limit - len(marker)
        head_len = remaining // 2
        tail_len = remaining - head_len
        return f"{text[:head_len].rstrip()}{marker}{text[-tail_len:].lstrip()}"

    def _validate_and_process(self, result: Dict[str, Any]) -> Dict[str, Any]:
        """Validation and post-processing results"""
        if not isinstance(result, dict):
            raise ValueError("Ontology result must be an object")

        raw_entities = result.get("entity_types")
        raw_edges = result.get("edge_types")
        if not isinstance(raw_entities, list):
            raw_entities = []
        if not isinstance(raw_edges, list):
            raw_edges = []
        if not isinstance(result.get("analysis_summary"), str):
            result["analysis_summary"] = ""

        # Normalize entity entries before touching their fields. LLMs
        # occasionally emit a bare string, null, or another scalar.
        entity_name_map: Dict[str, str] = {}
        processed_entities: List[Dict[str, Any]] = []
        seen_entity_names = set()
        for raw_entity in raw_entities:
            if isinstance(raw_entity, str):
                entity = {"name": raw_entity}
            elif isinstance(raw_entity, dict):
                entity = dict(raw_entity)
            else:
                logger.warning("Ignoring non-object ontology entity entry")
                continue

            original_name = entity.get("name")
            if not isinstance(original_name, str) or not original_name.strip():
                logger.warning("Ignoring ontology entity without a usable name")
                continue
            original_name = original_name.strip()
            normalized_name = _to_pascal_case(original_name)
            if normalized_name == "Unknown":
                continue
            if normalized_name in seen_entity_names:
                logger.warning(f"Duplicate entity type '{normalized_name}' removed during validation")
                entity_name_map[original_name] = normalized_name
                entity_name_map[original_name.lower()] = normalized_name
                continue

            if normalized_name != original_name:
                logger.warning(
                    f"Entity type name '{original_name}' auto-converted to '{normalized_name}'"
                )
            entity["name"] = normalized_name
            entity["attributes"] = normalize_ontology_attributes(
                entity.get("attributes", [])
            )
            if not isinstance(entity.get("examples"), list):
                entity["examples"] = []
            description = entity.get("description")
            if not isinstance(description, str) or not description:
                description = f"A {normalized_name} entity."
            entity["description"] = (
                description[:97] + "..." if len(description) > 100 else description
            )

            seen_entity_names.add(normalized_name)
            processed_entities.append(entity)
            entity_name_map[original_name] = normalized_name
            entity_name_map[original_name.lower()] = normalized_name
            entity_name_map[normalized_name] = normalized_name
            entity_name_map[normalized_name.lower()] = normalized_name

        result["entity_types"] = processed_entities

        # Backpack type definition
        person_fallback = {
            "name": "Person",
            "description": "Any individual person not fitting other specific person types.",
            "attributes": [
                {"name": "full_name", "type": "text", "description": "Full name of the person"},
                {"name": "role", "type": "text", "description": "Role or occupation"}
            ],
            "examples": ["ordinary citizen", "anonymous netizen"]
        }

        organization_fallback = {
            "name": "Organization",
            "description": "Any organization not fitting other specific organization types.",
            "attributes": [
                {"name": "org_name", "type": "text", "description": "Name of the organization"},
                {"name": "org_type", "type": "text", "description": "Type of organization"}
            ],
            "examples": ["small business", "community group"]
        }

        # Check if there is already a pocket type
        entity_names = {e["name"] for e in result["entity_types"]}
        has_person = "Person" in entity_names
        has_organization = "Organization" in entity_names

        # The type of cover that needs to be added
        fallbacks_to_add = []
        if not has_person:
            fallbacks_to_add.append(person_fallback)
        if not has_organization:
            fallbacks_to_add.append(organization_fallback)

        if fallbacks_to_add:
            current_count = len(result["entity_types"])
            needed_slots = len(fallbacks_to_add)

            # If added it will exceed 10 a,Some existing types need to be removed
            if current_count + needed_slots > MAX_ONTOLOGY_TYPES:
                # Calculate how many need to be removed
                to_remove = current_count + needed_slots - MAX_ONTOLOGY_TYPES
                # remove from end(Keep the more important concrete types from the front)
                result["entity_types"] = result["entity_types"][:-to_remove]

            # Add cover type
            result["entity_types"].extend(fallbacks_to_add)

        # Finally ensure that the limit is not exceeded(defensive programming)
        result["entity_types"] = result["entity_types"][:MAX_ONTOLOGY_TYPES]

        # Resolve edge endpoints only after entity fallback/capping, so an edge
        # cannot refer to a type that was removed to satisfy Zep's limits.
        valid_entity_names = {entity["name"] for entity in result["entity_types"]}
        for name in valid_entity_names:
            entity_name_map[name] = name
            entity_name_map[name.lower()] = name

        def resolve_entity_name(value: str) -> Optional[str]:
            stripped = value.strip()
            if stripped == "Entity":
                return stripped
            mapped = entity_name_map.get(stripped) or entity_name_map.get(stripped.lower())
            if mapped in valid_entity_names:
                return mapped
            pascal_name = _to_pascal_case(stripped)
            return pascal_name if pascal_name in valid_entity_names else None

        processed_edges: List[Dict[str, Any]] = []
        seen_edge_names = set()
        for raw_edge in raw_edges:
            if isinstance(raw_edge, str):
                # A bare edge name has no endpoints and cannot be installed in
                # Zep safely. Ignore it instead of inventing a relationship.
                logger.warning(f"Ignoring ontology edge without source_targets: {raw_edge}")
                continue
            elif isinstance(raw_edge, dict):
                edge = dict(raw_edge)
            else:
                logger.warning("Ignoring non-object ontology edge entry")
                continue

            original_name = edge.get("name")
            if not isinstance(original_name, str) or not original_name.strip():
                logger.warning("Ignoring ontology edge without a usable name")
                continue
            normalized_name = _to_upper_snake_case(original_name)
            if normalized_name == "UNKNOWN" or normalized_name in seen_edge_names:
                if normalized_name in seen_edge_names:
                    logger.warning(f"Duplicate edge type '{normalized_name}' removed during validation")
                continue
            if normalized_name != original_name:
                logger.warning(
                    f"Edge type name '{original_name}' auto-converted to '{normalized_name}'"
                )
            edge["name"] = normalized_name

            normalized_targets = []
            for source_target in normalize_ontology_source_targets(
                edge.get("source_targets", []),
                limit=None,
            ):
                source = resolve_entity_name(source_target["source"])
                target = resolve_entity_name(source_target["target"])
                if source and target:
                    normalized_targets.append({"source": source, "target": target})
            edge["source_targets"] = normalize_ontology_source_targets(
                normalized_targets
            )
            edge["attributes"] = normalize_ontology_attributes(
                edge.get("attributes", [])
            )
            description = edge.get("description")
            if not isinstance(description, str) or not description:
                description = f"A {normalized_name} relationship."
            edge["description"] = (
                description[:97] + "..." if len(description) > 100 else description
            )

            seen_edge_names.add(normalized_name)
            processed_edges.append(edge)
            if len(processed_edges) == MAX_ONTOLOGY_TYPES:
                break

        result["edge_types"] = processed_edges

        return result

    def generate_python_code(self, ontology: Dict[str, Any]) -> str:
        """
        Convert ontology definition to Python code(Similar to ontology.py)

        Args:
            ontology: ontology definition

        Returns:
            Python code string
        """
        code_lines = [
            '"""',
            'Custom entity type definition',
            'by MiroFish Automatically generated,Used for social public opinion simulation',
            '"""',
            '',
            'from pydantic import Field',
            'from zep_cloud.external_clients.ontology import EntityModel, EntityText, EdgeModel',
            '',
            '',
            '# ============== Entity type definition ==============',
            '',
        ]

        # Generate entity type
        for entity in ontology.get("entity_types", []):
            name = entity["name"]
            desc = entity.get("description", f"A {name} entity.")

            code_lines.append(f'class {name}(EntityModel):')
            code_lines.append(f'    """{desc}"""')

            attrs = entity.get("attributes", [])
            if attrs:
                for attr in attrs:
                    attr_name = attr["name"]
                    attr_desc = attr.get("description", attr_name)
                    code_lines.append(f'    {attr_name}: EntityText = Field(')
                    code_lines.append(f'        description="{attr_desc}",')
                    code_lines.append(f'        default=None')
                    code_lines.append(f'    )')
            else:
                code_lines.append('    pass')

            code_lines.append('')
            code_lines.append('')

        code_lines.append('# ============== Relationship type definition ==============')
        code_lines.append('')

        # Generate relationship type
        for edge in ontology.get("edge_types", []):
            name = edge["name"]
            # Convert to PascalCase Class name
            class_name = ''.join(word.capitalize() for word in name.split('_'))
            desc = edge.get("description", f"A {name} relationship.")

            code_lines.append(f'class {class_name}(EdgeModel):')
            code_lines.append(f'    """{desc}"""')

            attrs = edge.get("attributes", [])
            if attrs:
                for attr in attrs:
                    attr_name = attr["name"]
                    attr_desc = attr.get("description", attr_name)
                    code_lines.append(f'    {attr_name}: EntityText = Field(')
                    code_lines.append(f'        description="{attr_desc}",')
                    code_lines.append(f'        default=None')
                    code_lines.append(f'    )')
            else:
                code_lines.append('    pass')

            code_lines.append('')
            code_lines.append('')

        # Generate type dictionary
        code_lines.append('# ============== Type configuration ==============')
        code_lines.append('')
        code_lines.append('ENTITY_TYPES = {')
        for entity in ontology.get("entity_types", []):
            name = entity["name"]
            code_lines.append(f'    "{name}": {name},')
        code_lines.append('}')
        code_lines.append('')
        code_lines.append('EDGE_TYPES = {')
        for edge in ontology.get("edge_types", []):
            name = edge["name"]
            class_name = ''.join(word.capitalize() for word in name.split('_'))
            code_lines.append(f'    "{name}": {class_name},')
        code_lines.append('}')
        code_lines.append('')

        # generating edges source_targets mapping
        code_lines.append('EDGE_SOURCE_TARGETS = {')
        for edge in ontology.get("edge_types", []):
            name = edge["name"]
            source_targets = edge.get("source_targets", [])
            if source_targets:
                st_list = ', '.join([
                    f'{{"source": "{st.get("source", "Entity")}", "target": "{st.get("target", "Entity")}"}}'
                    for st in source_targets
                ])
                code_lines.append(f'    "{name}": [{st_list}],')
        code_lines.append('}')

        return '\n'.join(code_lines)
